steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/eldamo-build/eldamo:${_ELDAMO_VERSION}', '.' ]
images:
- 'gcr.io/eldamo-build/eldamo:${_ELDAMO_VERSION}'
substitutions:
  _ELDAMO_VERSION: 0.7.4
